### PR TITLE
responsivity for app and design fixes

### PR DESCRIPTION
**Pull request by JanPuskar**

### CODE REVIEW

**Comment by jindrichmynarz** [comment]
While this fixes some of the responsivity of the game screen (e.g., question correctly stacking under the game board), it also introduces vertical scrolling on the home page. As discussed, it might be better if the question appeared overlaid the game board on mobile devices to avoid needing to scroll.

**Comment by JanPuskar** [comment]
Add class 'active-question' to body or #app element when the player is answering the question. With .active-question class on parent the question will overlay the board game.

**Comment by jindrichmynarz** [comment]
Please also resolve the scrolling issue.

**Comment by jindrichmynarz** [comment]
Pull request abandoned by its author.

**Pull request closed without merging**
